name: Release package to the Maven Central Repository

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_JIRA_USERNAME
          server-password: OSSRH_JIRA_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD
      - name: Cache for maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache for yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-maven-semantic-release-v4.5.0
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup semantic-release
        run: |
          yarn global add @conveyal/maven-semantic-release@v4.5.0 semantic-release@15
          echo "::add-path::$(yarn global bin)"
      - name: Test
        run: mvn -B test
      - name: Release
        # maven-semantic-release requires "maven-settings.xml" in the workspace directory
        run: |
          mv ~/.m2/settings.xml maven-settings.xml
          semantic-release --branch master --prepare @conveyal/maven-semantic-release \
            --publish @semantic-release/github,@conveyal/maven-semantic-release \
            --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release \
            --verify-release @conveyal/maven-semantic-release\
            --use-conveyal-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
